---
title: Analysis R package for ntels Business Intelligence Team
author: <a href = "https://lovetoken.github.io">lovetoken</a>
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_height: 6
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
    keep_md: yes
---

```{r env, echo = F, warning = F, message = F}
pacman::p_load("knitr", "tidyverse", "ggplot2", "data.table", "mlbench")
library(ntelsBI)
opts_chunk$set(fig.path = "output/figure/", fig.align = "center", out.width = "80%", 
               warning = F, message = F)
```

<br><br>

## Tutorial

### Machine learning

`ml()` 함수를 이용하여 기계학습 훈련 및 평가를 수행할 수 있습니다.  

* CART 를 통한 `iris` 꽃잎분류

```{r}
ml(iris, "Species", method = "rpart") %>% fitSummary(type = "cla")
```

* GLM 을 통한 `Sonar` 의 `Class` 분류 (Class = "R" 이 주관심사일 경우)

```{r}
data(Sonar, package = "mlbench")
ml(Sonar, "Class", method = "glm") %>% fitSummary(type = "cla", positive = "R")
```

* Random forest 를 통한 `mtcars` mpg 예측

```{r}
ml(mtcars, "mpg", method = "rf") %>% fitSummary(type = "reg")
```

<br>

### Useful Preprocessing

* `range01()` function : Standardization 0 to 100

```{r}
x <- c(0, 2.59, 4.588, 5.0904, 11.11121)
range01(x) * 100 
```

* `csv2rda()` function : 워킹디렉토리의 table 형 파일들을 rda 포맷으로 변환시킵니다. 예를들면 csv 파일을 읽어들인 후 rda 포맷으로 변환시킵니다.

```{r eval = F}
csv2rda()
csv2rda(delete = T) # 변환 후 table 형의 원본파일들이 지워집니다.
```

<br><br>

## Install

```{r eval = F}
devtools::install_github("ntels-BI/ntelsBI")
```

<br><br>

## License

[GPL-3](https://www.gnu.org/licenses/gpl-3.0.en.html)
